### ISSUE TITLE
Question: Can galry be used as a backend for matplotlib?

### ISSUE THREAD

**Issue by ahmad88me** [rossant/galry#15]
as a faster alternative to TkAgg and Qt5Agg? (http://matplotlib.org/faq/usage_faq.html#what-is-a-backend)

**Comment by rossant** [comment]
No, unfortunately. Galry is no longer maintained. [Vispy](http://vispy.org/) is a newer alternative, there was a highly experimental matplotlib backend at some point but it is also unmaintained...

**Comment by ahmad88me** [comment]
Thanks 👍
